set_property PACKAGE_PIN K11 [get_ports areset_n_i]
set_property IOSTANDARD LVCMOS18 [get_ports areset_n_i]

set_property PACKAGE_PIN C8 [get_ports clk_20m_vcxo_i]
set_property IOSTANDARD LVCMOS18 [get_ports clk_20m_vcxo_i]
set_property PACKAGE_PIN U5 [get_ports clk_125m_gtp_n_i]
set_property PACKAGE_PIN U6 [get_ports clk_125m_gtp_p_i]
#set_property IOSTANDARD LVDS_25 [get_ports clk_125m_pllref_p_i]
set_property PACKAGE_PIN G7 [get_ports clk_125m_pllref_p_i]
set_property PACKAGE_PIN F7 [get_ports clk_125m_pllref_n_i]
#set_property IOSTANDARD LVDS_25 [get_ports clk_125m_pllref_n_i]


set_property PACKAGE_PIN N6 [get_ports plldac_sclk_o]
set_property IOSTANDARD LVCMOS18 [get_ports plldac_sclk_o]
set_property PACKAGE_PIN K8 [get_ports plldac_din_o]
set_property IOSTANDARD LVCMOS18 [get_ports plldac_din_o]
set_property PACKAGE_PIN K7 [get_ports pll25dac_cs_n_o]
set_property IOSTANDARD LVCMOS18 [get_ports pll25dac_cs_n_o]
set_property PACKAGE_PIN N7 [get_ports pll20dac_cs_n_o]
set_property IOSTANDARD LVCMOS18 [get_ports pll20dac_cs_n_o]

set_property PACKAGE_PIN J14 [get_ports eeprom_i2c_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports eeprom_i2c_sda_io]
set_property SLEW FAST [get_ports eeprom_i2c_sda_io]
set_property PACKAGE_PIN H14 [get_ports eeprom_i2c_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports eeprom_i2c_scl_io]
set_property SLEW FAST [get_ports eeprom_i2c_scl_io]

set_property PACKAGE_PIN K10 [get_ports thermo_id_tri_io]
set_property IOSTANDARD LVCMOS18 [get_ports thermo_id_tri_io]

set_property IOSTANDARD LVCMOS25 [get_ports sfp_i2c_sda_io]
set_property PACKAGE_PIN AB17 [get_ports sfp_i2c_sda_io]
set_property PACKAGE_PIN G16 [get_ports SFP_rx_los]
set_property IOSTANDARD LVCMOS18 [get_ports SFP_rx_los]
set_property PACKAGE_PIN V4 [get_ports SFP_rxp]
set_property PACKAGE_PIN K15 [get_ports SFP_tx_fault]
set_property IOSTANDARD LVCMOS18 [get_ports SFP_tx_fault]
set_property PACKAGE_PIN AB16 [get_ports sfp_i2c_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports sfp_i2c_scl_io]
set_property PACKAGE_PIN J15 [get_ports SFP_mod_abs]
set_property IOSTANDARD LVCMOS18 [get_ports SFP_mod_abs]
set_property PACKAGE_PIN G14 [get_ports sfp_rate_select_o]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_rate_select_o]
set_property PACKAGE_PIN G15 [get_ports SFP_tx_disable]
set_property IOSTANDARD LVCMOS18 [get_ports SFP_tx_disable]
set_property IOSTANDARD LVDS [get_ports clk_125m_pllref_p_i]

set_property PACKAGE_PIN AC18 [get_ports {pps_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {pps_p[0]}]
set_property PACKAGE_PIN AB26 [get_ports {clk_sys_62m5_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {clk_sys_62m5_p[0]}]
set_property PACKAGE_PIN AE10 [get_ports {clk_ref_125m_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {clk_ref_125m_p[0]}]

set_property PACKAGE_PIN AB22 [get_ports {dio_term[0]}]
set_property PACKAGE_PIN AB10 [get_ports {dio_term[1]}]
set_property PACKAGE_PIN Y13 [get_ports {dio_term[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_term[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_term[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_term[2]}]

set_property PACKAGE_PIN AB21 [get_ports {dio_oe_n[0]}]
set_property PACKAGE_PIN AD26 [get_ports {dio_oe_n[1]}]
set_property PACKAGE_PIN AF17 [get_ports {dio_oe_n[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_oe_n[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_oe_n[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dio_oe_n[2]}]


set_clock_groups -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks clk_sys]


