# Copy some required files
#file copy -force ../../board/fasec/component.xml ../../.
#file mkdir ../../xgui
#file copy -force ../../board/fasec/wrc_board_fasec_v4_1.tcl ../../xgui/.

# Run tcl script generated by Vivado
source ./wrc_board_quabo_ip.tcl
